version: '3'
services:
  elasticsearch-node-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    environment:
      - discovery.type=single-node
      - cluster.name=my-cluster
      - node.name=node-1
      - node.master=true
      - node.data=true
    ports:
      - "9200:9200"
      - "9300:9300"
  elasticsearch-node-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    environment:
      - discovery.type=single-node
      - cluster.name=my-cluster
      - node.name=node-2
      - node.master=false
      - node.data=true
    ports:
      - "9201:9200"
      - "9301:9300"
  elasticsearch-node-3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    environment:
      - discovery.type=single-node
      - cluster.name=my-cluster
      - node.name=node-3
      - node.master=false
      - node.data=true
    ports:
      - "9202:9200"
      - "9302:9300"
