version: '3'
services:
  producer:
    build:
      context: ./producer
    ports:
      - "3000:3000"
    links:
      - kafka
      - zookeeper  
# Zookeeper, single node
  zookeeper:
    image: wurstmeister/zookeeper:latest
    hostname: 'zookeeper'
    ports:
      - 2181:2181

 # kafka single node     
  kafka:
    image: wurstmeister/kafka:latest
    links:
      - zookeeper
    ports:
      - 9092:9092
    hostname: 'kafka'
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka   
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=test_topic:1:1

#kafdrop for topic/msg visualization
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
    ports:
      - 9011:9000
    depends_on:
      - kafka
networks:
    default:
        name: user-network
